### PR TITLE
Implemented config.json reader

### PR DESCRIPTION
**Pull request by chungjryan**
jsons are key value pairs so we treat user_config as a map.

### CODE REVIEW

**Comment by chungjryan** [comment]
please run make auto and verify that
"john smith" is printed

**Comment by ianhajra** [comment]
I'm getting the following error when I run it:

libc++abi: terminating due to uncaught exception of type nlohmann::json_abi_v3_11_3::detail::parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'J'
make: *** [auto] Abort trap: 6

Are you running it on linux or mac?

**Comment by chungjryan** [comment]
> I'm getting the following error when I run it:
> 
> libc++abi: terminating due to uncaught exception of type nlohmann::json_abi_v3_11_3::detail::parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'J' make: *** [auto] Abort trap: 6
> 
> Are you running it on linux or mac?

check /core/cfg/config.json and if it just says "John Smith" delete it :)

**Comment by chungjryan** [comment]
thats an old text file that will be replaced by a default value .json

**Comment by ianhajra** [comment]
It's printing "DEFAULT NAME" not "John Smith"

**Comment by chungjryan** [comment]
oh yeah whoops forgot that I changed it to that instead 😭

**Comment by ianhajra** [comment]
So it's working properly then?

**Comment by ianhajra** [comment]
It looks good from my end as long as that's the expected print

**Comment by chungjryan** [comment]
Yup :), also can you add the config.json to the gitignore, I tried but its not being ignored

**Comment by ianhajra** [comment]
Approved and merged

**Pull request merged**
